### PR TITLE
Support for spot instance worker groups without negatively impacting existing worker groups

### PR DESCRIPTION
**Pull request by mscifo**

### CODE REVIEW

**Comment by awithersdd** [comment]
This looks good, I'm going to clean up the diff and add: https://github.com/aws/aws-node-termination-handler will then talk to Taylor about merging to master. I have a separate holon branch I may move this to where I'm adding the new EBS CSI driver as well.

**Comment by taylorludwig** [comment]
Sounds good to me, yeah diff looks like its just showing a bunch of resources from the top got moved down to the bottom. 

I can run a plan on our other clusters to make sure its not trying to do anything else too. 

Fyi i just merged in two other PRs we had here. Let me know if they cause any problems. Thanks

**Comment by awithersdd** [comment]
I'll try the new version on one of our clusters over the weekend, looked fine to me, if I need to add an option I'll default it to on and PR everything so you can do the merge to master. As I mentioned I have some local changes for CSI drivers as well, I'm going to move this over to the holon branch so we can just use that, will PR once we are happy with it.

**Comment by taylorludwig** [comment]
ok perfect, yeah just feel free to merge this to master whenever you guys want. After closer look i see the big diff is caused because the wg options are moved to the `defaulted_worker_groups` local var - which makes sense. 

so this all looks fine with me. 

i've been issuing git tags on big changes too. For example what's on master right now is at `v1.2.0`  and our broadwing cluster just points at that anyways

**Review by taylorludwig — APPROVED** [review]

**Comment by awithersdd** [comment]
Merging this now, didn't get CSI changes done yet

**Pull request merged**
